### ISSUE TITLE
Add Laravel 5.5 compatibility

### ISSUE THREAD

**Issue by dzanfardino** [mailjet/laravel-mailjet#8]

**Comment by Nightbr** [comment]
Hey,

you can fork it and update the composer.json

```
"require": {
    "laravel/framework": "5.5.*",
    ...
```
Give us feedback, make a PR and contribute!

**Comment by dzanfardino** [comment]
hi @Nightbr, I'm actually doing that, however, I think there are other conflicts:

```

Problem 1
    - Conclusion: remove swiftmailer/swiftmailer v6.0.1
    - Conclusion: remove laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.1
    - Conclusion: don't install laravel/framework v5.5.0
    - Conclusion: don't install swiftmailer/swiftmailer v6.0.1
    - Installation request for laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev, v5.5.0, v5.5.1, v5.5.2].
    - Installation request for mailjet/laravel-mailjet dev-l55 -> satisfiable by mailjet/laravel-mailjet[dev-l55].
    - Conclusion: don't install swiftmailer/swiftmailer v5.4.8
    - mailjet/laravel-mailjet dev-l55 requires mailjet/mailjet-swiftmailer ^1.0 -> satisfiable by mailjet/mailjet-swiftmailer[1.0-beta.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5].
    - mailjet/mailjet-swiftmailer 1.0-beta.2 requires swiftmailer/swiftmailer ~5.4 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8].
    - mailjet/mailjet-swiftmailer 1.0.0 requires swiftmailer/swiftmailer ~5.4 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8].
    - mailjet/mailjet-swiftmailer 1.0.1 requires swiftmailer/swiftmailer ~5.4 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8].
    - mailjet/mailjet-swiftmailer 1.0.2 requires swiftmailer/swiftmailer ~5.4 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8].
    - mailjet/mailjet-swiftmailer 1.0.3 requires swiftmailer/swiftmailer ~5.4 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8].
    - mailjet/mailjet-swiftmailer 1.0.4 requires swiftmailer/swiftmailer ~5.4 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8].
    - mailjet/mailjet-swiftmailer 1.0.5 requires swiftmailer/swiftmailer ~5.4 -> satisfiable by swiftmailer/swiftmailer[5.x-dev, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8].
    - Can only install one of: swiftmailer/swiftmailer[6.0.x-dev, 5.x-dev].
    - Can only install one of: swiftmailer/swiftmailer[v5.4.0, 6.0.x-dev].
    - Can only install one of: swiftmailer/swiftmailer[v5.4.1, 6.0.x-dev].
    - Can only install one of: swiftmailer/swiftmailer[v5.4.2, 6.0.x-dev].
    - Can only install one of: swiftmailer/swiftmailer[v5.4.3, 6.0.x-dev].
    - Can only install one of: swiftmailer/swiftmailer[v5.4.4, 6.0.x-dev].
    - Can only install one of: swiftmailer/swiftmailer[v5.4.5, 6.0.x-dev].
    - Can only install one of: swiftmailer/swiftmailer[v5.4.6, 6.0.x-dev].
    - Can only install one of: swiftmailer/swiftmailer[v5.4.7, 6.0.x-dev].
    - laravel/framework 5.5.x-dev requires swiftmailer/swiftmailer ~6.0 -> satisfiable by swiftmailer/swiftmailer[v6.0.1, 6.0.x-dev, v6.0.0].
    - Conclusion: don't install swiftmailer/swiftmailer v6.0.0|install swiftmailer/swiftmailer v5.4.8


```

**Comment by Nightbr** [comment]
After a quick look this conflict comes from our mailjet/MailjetSwiftMailer package which requires `"swiftmailer/swiftmailer": "~5.4"`. [Here](https://github.com/mailjet/MailjetSwiftMailer/blob/master/composer.json#L10)

And in laravel/framework 5.5 it required "swiftmailer/swiftmailer": "~6.0". [Here](https://github.com/laravel/framework/blob/5.5/composer.json#L30)

We need to upgrade our MailjetSwiftMailer project and test it against swiftmailer 6.0 library...

**Comment by Nightbr** [comment]
The thing is, the new dependencies (swiftmailer 6.0 and Laravel 5.5) require php >=7.0.0

The question here is: Will we upgrade all our library/bundle/package to php >= 7.0.0 and drop php 5.6 support?

@latanasov, @arnaudbreton

**Comment by Nightbr** [comment]
Or we could set into our composer.json:
`"laravel/framework": ">=5.4"`
and
`"swiftmailer/swiftmailer": ">=5.4"`

But we need some tests with latest dependencies versions (only for major version).

I will try to implement this method: [here](https://dyrynda.com.au/blog/testing-multiple-dependency-versions-with-travis-ci)

**Comment by Nightbr** [comment]
M'okay it will not be simple... Because swiftmailer create huge BC-change between v5 and v6... We need to change our library MailjetSwiftMailer completely such as Laravel have done in its framework [see here](https://github.com/laravel/framework/commit/21f7240f68c03651d5f55927aed120651b2e05ff).

[EDIT] Some tests to understand the real problem:
The problem is the class Swift_Mime_Message which change to Swift_Mime_SimpleMessage in v6.

Here is, v5 with Swift_Mime_Message

``` shell
 $ composer require swiftmailer/swiftmailer:5.4.8
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating swiftmailer/swiftmailer (v6.0.1 => v5.4.8) Loading from cache
Writing lock file
Generating autoload files
$ vendor/bin/phpunit -c .
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

.Running test for SendAPI v3.1........Running test for SendAPI v3.......                                                  16 / 16 (100%)

Time: 45 ms, Memory: 8.00MB

OK (16 tests, 198 assertions)
```

But if I replace Swift_Mime_Message by Swift_Mime_SimpleMessage (hope some retrocompatibility...)

``` shell
$ vendor/bin/phpunit -c .
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

PHP Fatal error:  Declaration of Mailjet\MailjetSwiftMailer\SwiftMailer\MailjetTransport::send(Swift_Mime_SimpleMessage $message, &$failedRecipients = NULL) must be compatible with Swift_Transport::send(Swift_Mime_Message $message, &$failedRecipients = NULL) in /home/nightbringer/Dev/MailjetSwiftMailer/SwiftMailer/MailjetTransport.php on line 19
```
It just doesn't work...

If I upgrade to swiftmailer v6

``` shell
$ composer require swiftmailer/swiftmailer:~6.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating swiftmailer/swiftmailer (v5.4.8 => v6.0.1) Loading from cache
Writing lock file
Generating autoload files
$ vendor/bin/phpunit -c .
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

.Running test for SendAPI v3.1........Running test for SendAPI v3.......                                                  16 / 16 (100%)

Time: 48 ms, Memory: 8.00MB

OK (16 tests, 198 assertions)
```

It works....

So we will have to make a choice and create BC-code if we upgrade and publish a new release.

**Comment by Nightbr** [comment]
Here is the branch with SwiftMailer ~6.0 support: https://github.com/mailjet/MailjetSwiftMailer/tree/upgradeToSwiftmailer6

**Comment by Nightbr** [comment]
We will have the same problem with Symfony:
https://packagist.org/packages/symfony/swiftmailer-bundle#v3.0.0
and
https://packagist.org/packages/symfony/swiftmailer-bundle#v2.6.3

**Comment by valentinfily** [comment]
Laravel 5.5 compatibility would be much appreciated!

**Comment by Nightbr** [comment]
@potioventures create a fork and use this branch of https://github.com/mailjet/MailjetSwiftMailer/tree/upgradeToSwiftmailer6

**Comment by valentinfily** [comment]
@Nightbr Thank you

**Comment by damien-lechopier** [comment]
Hello,

Can you explain more to use this repo with Laravel v5.5
I tried to fork this repo and try this on my laravel composer.json :

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/xxx/laravel-mailjet"
        }
    ],
"require": {
        "mailjet/laravel-mailjet": "dev-master",
},

```

But I have this message and I can't do anything :

"mailjet/laravel-mailjet 1.1.0 requires laravel/framework 5.4 .* -> satisfiable by laravel/framework[5.4."

Help please

**Comment by Nightbr** [comment]
@damien-lechopier 

Hello,

I have created a new branch for handle laravel 5.5, in you composer.json load the dependencies on the branch laravel5.5:

`"mailjet/laravel-mailjet": "dev-laravel5.5",`

Let me know

**Comment by Nightbr** [comment]
@latanasov In order to resume the problem here:
Laravel 5.5 require:

1. php 7 minimum (we will drop php5.6 support)
2. SwiftMailer 6 (which introduce BC-Change) so we will drop support of SwiftMailer < 6

The better we can do is to create a v2.0.0 which upgrade to php 7 minimum and SwiftMailer 6 in order to handle Laravel 5.5. For old laravel version, we still can use v1.x.x.

**Comment by damien-lechopier** [comment]
@Nightbr

It seems to work.
Thank you very much!

**Comment by latanasov** [comment]
Hi @Nightbr, sounds good to me. The only bottleneck seems to be our [ php-wrapper](https://github.com/mailjet/mailjet-apiv3-php) which currently supports PHP >= 5.4 (we've been thinking for a while to drop that) . Did you get any composer dependency warnings ?

**Comment by Nightbr** [comment]
Hey, no warning if it's superior or equal to 5.4
But I think every PHP project should think to upgrade to PHP 7 (better performance, better stability and code maintenability...)

**Comment by hurano** [comment]
I can't install this plugin. I am using laravel 5.5. Here is my composer

```yaml
"require": {
        "php": ">=7.0.0",
        "baum/baum": "^1.1",
        "fideloper/proxy": "~3.3",
        "guzzlehttp/guzzle": "^6.3",
        "hesto/multi-auth": "^2.0",
        "intervention/image": "^2.4",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "mailjet/laravel-mailjet": "dev-laravel5.5",
        "mcamara/laravel-localization": "^1.3",
        "swiftmailer/swiftmailer": "^6.0",
        "wildbit/postmark-php": "^2.3"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.1",
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "hisorange/browser-detect": "2.*",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0"
    }
```

I got this error.
  Problem 1
    - Installation request for mailjet/laravel-mailjet dev-laravel5.5 -> satisfiable by mailjet/laravel-mailjet[dev-laravel5.5].
    - mailjet/laravel-mailjet dev-laravel5.5 requires mailjet/mailjet-swiftmailer dev-upgradeToSwiftmailer6 -> satisfiable by mailjet/mailjet-swiftmailer[dev-upgradeToSwiftmailer6] but these conflict with your requirements or minimum-stability.

**Comment by Nightbr** [comment]
@hurano verify your minimum-stability and see this: http://webtips.krajee.com/setting-composer-minimum-stability-application/

**Comment by aldhonie** [comment]
i got the same error as @hurano .
this is my composer.

`"minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "guzzlehttp/guzzle": "^6.3",
        "laracasts/utilities": "^3.0",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "swiftmailer/swiftmailer": "^6.0",
        "mailjet/laravel-mailjet": "dev-laravel5.5"
    },`
``

**Comment by Nightbr** [comment]
Like I said, change your minimum-stability:
```yaml
"minimum-stability": "dev",
"prefer-stable": true
```

**Comment by aldhonie** [comment]
ok, ill try, thanks @Nightbr

**Comment by aldhonie** [comment]
its my composer @Nightbr 

`"minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "guzzlehttp/guzzle": "^6.3",
        "laracasts/utilities": "^3.0",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "mailjet/mailjet-apiv3-php": "^1.2",
        "mailjet/laravel-mailjet": "dev-laravel5.5"
    },`

and i got this message:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/framework[v5.5.21, 5.4.x-dev].
    - Can only install one of: laravel/framework[5.4.x-dev, v5.5.21].
    - Can only install one of: laravel/framework[5.4.x-dev, v5.5.21].
    - mailjet/laravel-mailjet 1.1.0 requires laravel/framework 5.4.* -> satisfiable by laravel/framework[5.4.x-dev].
    - Installation request for mailjet/laravel-mailjet ^1.1 -> satisfiable by mailjet/laravel-mailjet[1.1.0].
    - Installation request for laravel/framework (locked at v5.5.21, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.21].

**Comment by Nightbr** [comment]
this is weird... 
`- Installation request for mailjet/laravel-mailjet ^1.1 -> satisfiable by mailjet/laravel-mailjet[1.1.0].` this should not be ^1.1 but the branch laravel5.5...

Try to update composer, `composer self-update`

**Comment by aldhonie** [comment]
ok, lets try @Nightbr

**Comment by Nightbr** [comment]
Working on my fresh project:

`$ composer create-project --prefer-dist laravel/laravel blog`

Edit composer.json

```yaml
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "mailjet/laravel-mailjet": "dev-laravel5.5"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}
```
Run composer update:

```shell

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing psr/http-message (1.0.1) Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2) Loading from cache
  - Installing guzzlehttp/promises (v1.3.1) Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0) Loading from cache
  - Installing mailjet/mailjet-apiv3-php (v1.2.0) Downloading: 100%         
  - Installing mailjet/mailjet-swiftmailer (dev-upgradeToSwiftmailer6 17c40ed) Downloading: Connecti Downloading: 100%         
  - Installing mailjet/laravel-mailjet (dev-laravel5.5 bfe20c4) Downloading: 100%         
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Package manifest generated successfully.

```

My compose version:

```
$ composer -V
Composer version 1.3.2 2017-01-27 18:23:41
```

It's working great, I think you should check your config or try to reproduce my step and compare with your project.
